sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.mongodb-binaries
notifications:
  email: true
node_js:
  - "8.10.0"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH
script:
  - yarn run test
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - if [[ "$TRAVIS_JOB_NUMBER" == *.1 && "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash <(curl -s https://codecov.io/bash); fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
